[tools]
# Erlang
erlang = ["latest", "28", "27"]
rebar = "latest"
# Build dependencies
gh = "latest"
git-cliff = "latest"
glow = "latest"
markdownlint-cli2 = "latest"
shellcheck = "latest"
yamllint = "latest"
shfmt = "latest"
actionlint = "latest"

[tasks.lint]
depends = ["lint:*"]

[tasks."lint:yaml"]
run = "yamllint ."

[tasks."lint:md"]
run = "markdownlint-cli2 *.md .github/**/*.md"

[tasks."lint:sh"]
run = [
    "shellcheck -o all **/*.sh",
    "shfmt --diff **/*.sh"
]

[tasks."lint:action"]
run = "actionlint"

[tasks.ci]
depends = ["lint:*"]
run = "rebar3 ci"

[tasks.changelog]
description = "Update the changelog"
run = 'git-cliff --exclude-path="scripts/**"'

[tasks."release"]
description = "Dry-run a release of the library"
run = 'scripts/release.sh'
