[tasks.lint]
depends = ["lint:**"]

[tasks."lint:yaml"]
run = "yamllint ."

[tasks."lint:md"]
run = "markdownlint-cli2 *.md .github/**/*.md"

[tasks."lint:erl"]
run = "rebar3 fmt --check"

[tasks.ci]
depends = ["lint:**"]
run = "rebar3 as test ci"
