[tools]
# Erlang
erlang = ["27", "28", "latest"]
rebar = "latest"
# Build dependencies
gh = "latest"
git-cliff = "latest"
glow = "latest"
markdownlint-cli2 = "latest"
shellcheck = "latest"
yamllint = "latest"
shfmt = "latest"

[tasks.lint]
depends = ["lint:*"]

[tasks."lint:yaml"]
run = "yamllint ."

[tasks."lint:md"]
run = "markdownlint-cli2 *.md .github/**/*.md"

[tasks."lint:shell"]
run = [
    "shellcheck -o all **/*.sh",
    "shfmt --diff **/*.sh"
]

[tasks."lint:erl"]
run = "rebar3 fmt --check"

[tasks.ci]
depends = ["lint:*"]
run = "rebar3 as test ci"

[tasks.changelog]
description = "Update the changelog"
run = 'git-cliff'

[tasks."release"]
description = "Dry-run a release of the library"
run = 'scripts/release.sh'
