---
name: CI

on:
  - push

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  lint:
    name: Lint

    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - uses: jdx/mise-action@v4

      - run: mise run --output=keep-order lint

  test:
    name: Erlang ${{matrix.erlang}}

    runs-on: ubuntu-24.04

    strategy:
      matrix:
        erlang: ["27", "28"]

    env:
      MISE_ERLANG_VERSION: ${{matrix.erlang}}

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - uses: jdx/mise-action@v4

      - uses: actions/cache@caa296126883cff596d87d8935842f9db880ef25 # v5
        with:
          path: |
            ~/.cache/rebar3
            _build
            !_build/test/logs
          # yamllint disable-line rule:line-length
          key: rebar3-${{runner.os}}_${{runner.arch}}-erlang-${{matrix.erlang}}-rebar-${{hashFiles('rebar.lock')}}

      - run: mise run --output=keep-order verify:rebar verify:elp test
