---
name: CI

on:
  - push

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  lint:
    name: Lint

    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: jdx/mise-action@v4

      - run: mise run --output=keep-order lint

  test:
    name: Erlang ${{matrix.erlang}}

    runs-on: ubuntu-24.04

    strategy:
      matrix:
        erlang: ["27", "28"]

    env:
      MISE_ERLANG_VERSION: ${{matrix.erlang}}

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: jdx/mise-action@v4

      - uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5
        with:
          path: |
            ~/.cache/rebar3
            _build
            !_build/test/logs
          # yamllint disable-line rule:line-length
          key: rebar3-${{runner.os}}_${{runner.arch}}-erlang-${{matrix.erlang}}-rebar-${{hashFiles('rebar.lock')}}

      - run: mise run --output=keep-order verify:rebar verify:elp test
