---
name: Erlang CI
"on":
  - push
jobs:
  ci:
    name: Erlang CI
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
    steps:
      - name: Checkout code
        # yamllint disable-line
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1

      - name: Install Erlang
        # yamllint disable-line
        uses: erlef/setup-beam@5304e04ea2b355f03681464e683d92e3b2f18451 # v1.18.2
        id: setup-beam
        with:
          version-file: .tool-versions
          version-type: strict

      - name: Restore/save from/to cache
        # yamllint disable-line
        uses: actions/cache@2cdf405574d6ef1f33a1d12acccd3ae82f47b3f2 # v4.1.0
        with:
          path: |
            _build
            ~/.cache/rebar3
            !_build/test/logs
          key: "cache-for\
                -os-${{runner.os}}\
                -otp-${{steps.setup-beam.outputs.otp-version}}\
                -rebar3-${{steps.setup-beam.outputs.rebar3-version}}\
                -hash-${{hashFiles('rebar.lock', 'rebar.config')}}"

      - name: Check formatting
        run: rebar3 fmt --check

      - name: Continuous Integration
        run: rebar3 as test ci
