---
name: Erlang CI

'on':
  - push

jobs:
  ci:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        erlang: ["27", "28"]
    name: Erlang ${{matrix.erlang}}
    steps:

      - name: Checkout code
        # yamllint disable-line
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - name: Restore/save from/to cache
        # yamllint disable-line
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          path: |
            _build
            ~/.cache/rebar3
            !_build/test/logs
          key: "cache-for\
                -os-${{runner.os}}\
                -erlang-${{matrix.erlang}}\
                -hash-${{hashFiles('rebar.lock', 'rebar.config')}}"

      - name: Install dependencies
        uses: jdx/mise-action@v2
        with:
          mise_toml: |
            [tools]
            erlang = "${{matrix.erlang}}"

      - name: Run CI checks
        run: rebar3 ci
