---
name: Project lint
"on":
  - push
jobs:
  ci:
    name: Project lint
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
    steps:
      - name: Checkout code
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0

      # uses .markdownlint.yml for configuration
      - name: markdownlint
        # yamllint disable-line
        uses: DavidAnson/markdownlint-cli2-action@db43aef879112c3119a410d69f66701e0d530809 # v17.0.0
        with:
          globs: |
            .github/**/*.md
            *.md
      - name: yamllint
        # yamllint disable-line
        uses: ibiqlik/action-yamllint@2576378a8e339169678f9939646ee3ee325e845c # v3.1.1
        with:
          strict: true
          config_file: .yamllint.yml

      - name: actionlint
        # yamllint disable-line
        uses: reviewdog/action-actionlint@15a7a477ab5ab768a41c39b2c53970bf151c73f3 # v1.56.0
        env:
          SHELLCHECK_OPTS: -o all

      - name: action-sh-checker
        # yamllint disable-line
        uses: luizm/action-sh-checker@17bd25a6ee188d2b91f677060038f4ba37ba14b2 # v0.9.0
        env:
          SHELLCHECK_OPTS: -o all
          SHFMT_OPTS: -i 4 -d
