---
name: Project lint

'on':
  - push

jobs:
  ci:
    name: Project lint
    runs-on: ubuntu-24.04
    steps:

      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Install dependencies
        uses: jdx/mise-action@v3

      - name: Lint Markdown
        run: mise run lint:md

      - name: Lint YAML
        run: mise run lint:yaml

      - name: Lint shell scripts
        run: mise run lint:sh

      - name: Lint GitHub Actions
        run: mise run lint:action
