---
name: Project lint

'on':
  - push

jobs:
  ci:
    name: Project lint
    runs-on: ubuntu-24.04
    steps:

      - name: Checkout code
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1

      - name: Install dependencies
        uses: jdx/mise-action@v2

      - name: Lint Markdown
        run: mise run lint:md

      - name: Lint YAML
        run: mise run lint:yaml

      - name: Lint shell scripts
        run: mise run lint:sh

      - name: Lint GitHub Actions
        run: mise run lint:action
