---
name: Project lint

'on':
  - push

jobs:
  ci:
    name: Project lint
    runs-on: ubuntu-24.04
    steps:

      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install dependencies
        uses: jdx/mise-action@v2

      - name: Lint Markdown
        run: mise run lint:md

      - name: Lint YAML
        run: mise run lint:yaml

      - name: Lint shell scripts
        run: mise run lint:sh

      - name: Lint GitHub Actions
        run: mise run lint:action
